version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lucasilverentand-privado-vpn_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/lucasilverentand/privado-proxy:dashboard@sha256:b21cce882c88546a692cc5ca730d0e3215df7f41889564da141eac35dffae649
    restart: on-failure
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TZ: ${TZ:-Etc/UTC}
      SOCK_PORT: "1080"
      DASHBOARD_ENABLED: "true"
      DASHBOARD_PORT: "8080"
      PRIVADO_USERNAME: ${PRIVADO_USERNAME:-}
      PRIVADO_PASSWORD: ${PRIVADO_PASSWORD:-}
      PRIVADO_SERVER: ${PRIVADO_SERVER:-}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
