version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lucasilverentand-jellyfin_server_1
      APP_PORT: 8096

  server:
    image: lscr.io/linuxserver/jellyfin:latest@sha256:a569ae0bfbd67ca404ae51f54cead7a2522d270179f57b3d12cf80ebff5d683b
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ:-Etc/UTC}
      JELLYFIN_PublishedServerUrl: ${APP_DOMAIN:-}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/cache:/cache
      - ${UMBREL_ROOT}/data/storage/downloads:/data
