services:
  app_proxy:
    environment:
      APP_HOST: lucasilverentand-crafty_web_1
      APP_PORT: 8080

  web:
    image: nginx:1.29-alpine@sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de
    restart: on-failure
    depends_on:
      - server
    volumes:
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/nginx.conf:ro

  server:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.10.7@sha256:67c2cbab1c88b75efb41b2970b1faca1a736b3532f6d1a806a7fe3f81664a199
    restart: on-failure
    stop_grace_period: 1m
    environment:
      TZ: ${TZ:-Etc/UTC}
    ports:
      - "8123:8123"
      - "19132:19132/udp"
      - "25500-25600:25500-25600"
    volumes:
      - ${APP_DATA_DIR}/data/backups:/crafty/backups
      - ${APP_DATA_DIR}/data/logs:/crafty/logs
      - ${APP_DATA_DIR}/data/servers:/crafty/servers
      - ${APP_DATA_DIR}/data/config:/crafty/app/config
      - ${APP_DATA_DIR}/data/import:/crafty/import
